### ISSUE TITLE
Error on Pizzas page

### ISSUE THREAD

**Issue by gitamo626** [lohithgn/blazor-aspnetwebapi-efcore-sample#1]
Thanks for putting this bundle of code together and making it publicly available. So, I configured startup projects for the solution like so:
![image](https://github.com/user-attachments/assets/1c655243-8c93-497a-b6ae-bb9df022d643)

Both the backend and the front pieces launched just fine. Then when I navigate to the Pizzas page and click on any of the pizzas, I get this error:

> fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
>       Unhandled exception in circuit 'zVRCZid6RWpxYxiDk_SUUE_X3Fw1ISQ2XmIQvsEqusg'.
>       System.InvalidOperationException: Cannot provide a value for property 'SauceService' on type 'Contoso.Pizza.AdminUI.Components.Pages.Pizza.PizzaUpsertPanel'. There is no registered service of type 'Contoso.Pizza.AdminUI.Services.SauceService'.
>          at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
>          at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
>          at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
>          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
>          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
>          at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
>          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
>          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

![image](https://github.com/user-attachments/assets/c8d73d37-2dc7-4a6a-b8ea-e40883c27452)

And why would this work on your side and on mine fail miserably? Any ideas? Thank you!

**Comment by gitamo626** [comment]
Ok, here it is - PizzaUpsertPanel was requesting services be injected by class type rather than by interface (how they were registered).

![Screenshot 2024-11-27 231435](https://github.com/user-attachments/assets/e5dda64e-89f7-41b2-bd52-bd8c173f5ac7)

vs

![image](https://github.com/user-attachments/assets/3dcf1c56-2899-4d15-9026-ae15bdf426fb)


Good luck, y'all
